[package]
name = "canvas-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive"] }
confy = "0.5.1"
fuzzy-matcher = "0.3.7"
graphql_client = { version = "0.12.0", features = ["reqwest", "reqwest-blocking"] }
indicatif = "0.17.3"
inquire = "0.5.3"
reqwest = "0.11.14"
serde = "1.0.152"
serde_derive = "1.0.152"
tokio = {version = "1.25.0", features = ["full"] }
url = "2.3.1"
