[package]
name = "canvas-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.23", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive"] }
confy = "0.5.1"
graphql_client = "0.12.0"
reqwest = "0.11.14"
serde = "1.0.152"
serde_derive = "1.0.152"
url = "2.3.1"
